### ISSUE TITLE
Repository naming convention

### ISSUE THREAD

**Issue by hot007** [aus-ref-clim-data-nci/aus-ref-clim-data-nci#3]
This ship may have already sailed, sorry, but Paola and I were discussing this morning that maybe the name of this repo/org is a little misleading, as it might sort of imply being NCI-lead, rather than ACS-lead and hosted at NCI.
Suggested possible convention could be "ACS-ref-clim-data-NCI", which would leave the door open to, say, "ACS-ref-clim-data-S3" etc in the future, with the same base string.
I realise this should have come up a couple of months ago and maybe it's a bit late now, but just a thought.
-Claire

**Comment by DamienIrving** [comment]
That's a good point...

I like the idea of ending with NCI (like you say, so we could use S3 or something in future), but I wonder about starting with ACS given that in future I'd like to think other partners (like NESP) would come on board.

The "Australian Community Reference Climate Data Collection @ NCI" (`aus-ref-clim-data-nci`) might work? (Probably need the word community in there otherwise it sounds like the datasets are just Australia when most are global.)

**Comment by hot007** [comment]
Yes I like that as the full name. We can probably live with or without 'community' in the repo name, reference data for Australia doesn't necessarily imply limited to Australia, but I do get what you mean so making it clear in the repo's full name is good.

**Comment by DamienIrving** [comment]
Done :smile:
https://github.com/aus-ref-clim-data-nci
